# GitHub labels configuration
# This file helps document what labels should exist
# You still need to create them manually in GitHub

- name: dependencies
  color: '0366d6'
  description: 'Dependency updates'

- name: python
  color: '3776ab'
  description: 'Python-related changes'

- name: javascript
  color: 'f7df1e'
  description: 'JavaScript/Node.js related changes'

- name: admin
  color: '5319e7'
  description: 'Admin panel related changes'

- name: docker
  color: '2496ed'
  description: 'Docker related changes'

- name: github-actions
  color: '000000'
  description: 'GitHub Actions workflow changes'

- name: security
  color: 'd73a4a'
  description: 'Security updates or fixes'

- name: bug
  color: 'd73a4a'
  description: 'Something isn't working'

- name: enhancement
  color: 'a2eeef'
  description: 'New feature or request'

- name: documentation
  color: '0075ca'
  description: 'Improvements or additions to documentation'

- name: good first issue
  color: '7057ff'
  description: 'Good for newcomers'

- name: help wanted
  color: '008672'
  description: 'Extra attention is needed'